x-veld:
  executable:
    about:
      description: "dummy veld for testing and showcasing"
    input:
      a:
        type: "xml"
        path: /veld/input/data.xml
        content: "dummy data"
      b:
        type: "environment variable"
        id: "user"
      c:
        type: "environment variable"
        id: "password"
      d:
        type: "environment variable"
        id: "host"
      e:
        type: "environment variable"
        id: "database_name"
    output:
      type: "BaseX http endpoint"
    docker_context:
      type: "docker network"
      optional: true

services:
  veld:
    image: curlimages/curl:8.2.1 
    volumes:
      - ./load.sh:/veld/executable/load.sh
    command: sh /veld/executable/load.sh

